package com.snowlink.phmapi.model;

import java.util.Date;

public class SysColdstore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.company_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.Code
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.Name
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.Alias
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.Descp
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String descp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.Logo
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.mainImg
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String mainimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.Status
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.Region
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.Type
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.Longitude
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Float longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.Latitude
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Float latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.Contactor
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String contactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.MobilePhone
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String mobilephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.Email
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.Province
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.City
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.County
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.Address
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.Website
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String website;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.pczxml
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String pczxml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.mobilezxml
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String mobilezxml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.create_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.creator
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.update_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore.updater
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.ID
     *
     * @return the value of sys_coldstore.ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.ID
     *
     * @param id the value for sys_coldstore.ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.company_id
     *
     * @return the value of sys_coldstore.company_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.company_id
     *
     * @param companyId the value for sys_coldstore.company_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.Code
     *
     * @return the value of sys_coldstore.Code
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.Code
     *
     * @param code the value for sys_coldstore.Code
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.Name
     *
     * @return the value of sys_coldstore.Name
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.Name
     *
     * @param name the value for sys_coldstore.Name
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.Alias
     *
     * @return the value of sys_coldstore.Alias
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.Alias
     *
     * @param alias the value for sys_coldstore.Alias
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.Descp
     *
     * @return the value of sys_coldstore.Descp
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getDescp() {
        return descp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.Descp
     *
     * @param descp the value for sys_coldstore.Descp
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setDescp(String descp) {
        this.descp = descp == null ? null : descp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.Logo
     *
     * @return the value of sys_coldstore.Logo
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.Logo
     *
     * @param logo the value for sys_coldstore.Logo
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.mainImg
     *
     * @return the value of sys_coldstore.mainImg
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getMainimg() {
        return mainimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.mainImg
     *
     * @param mainimg the value for sys_coldstore.mainImg
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setMainimg(String mainimg) {
        this.mainimg = mainimg == null ? null : mainimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.Status
     *
     * @return the value of sys_coldstore.Status
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.Status
     *
     * @param status the value for sys_coldstore.Status
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.Region
     *
     * @return the value of sys_coldstore.Region
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.Region
     *
     * @param region the value for sys_coldstore.Region
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.Type
     *
     * @return the value of sys_coldstore.Type
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.Type
     *
     * @param type the value for sys_coldstore.Type
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.Longitude
     *
     * @return the value of sys_coldstore.Longitude
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.Longitude
     *
     * @param longitude the value for sys_coldstore.Longitude
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.Latitude
     *
     * @return the value of sys_coldstore.Latitude
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.Latitude
     *
     * @param latitude the value for sys_coldstore.Latitude
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.Contactor
     *
     * @return the value of sys_coldstore.Contactor
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getContactor() {
        return contactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.Contactor
     *
     * @param contactor the value for sys_coldstore.Contactor
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setContactor(String contactor) {
        this.contactor = contactor == null ? null : contactor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.MobilePhone
     *
     * @return the value of sys_coldstore.MobilePhone
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.MobilePhone
     *
     * @param mobilephone the value for sys_coldstore.MobilePhone
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.Email
     *
     * @return the value of sys_coldstore.Email
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.Email
     *
     * @param email the value for sys_coldstore.Email
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.Province
     *
     * @return the value of sys_coldstore.Province
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.Province
     *
     * @param province the value for sys_coldstore.Province
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.City
     *
     * @return the value of sys_coldstore.City
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.City
     *
     * @param city the value for sys_coldstore.City
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.County
     *
     * @return the value of sys_coldstore.County
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.County
     *
     * @param county the value for sys_coldstore.County
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.Address
     *
     * @return the value of sys_coldstore.Address
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.Address
     *
     * @param address the value for sys_coldstore.Address
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.Website
     *
     * @return the value of sys_coldstore.Website
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.Website
     *
     * @param website the value for sys_coldstore.Website
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.pczxml
     *
     * @return the value of sys_coldstore.pczxml
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getPczxml() {
        return pczxml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.pczxml
     *
     * @param pczxml the value for sys_coldstore.pczxml
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setPczxml(String pczxml) {
        this.pczxml = pczxml == null ? null : pczxml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.mobilezxml
     *
     * @return the value of sys_coldstore.mobilezxml
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getMobilezxml() {
        return mobilezxml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.mobilezxml
     *
     * @param mobilezxml the value for sys_coldstore.mobilezxml
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setMobilezxml(String mobilezxml) {
        this.mobilezxml = mobilezxml == null ? null : mobilezxml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.create_date
     *
     * @return the value of sys_coldstore.create_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.create_date
     *
     * @param createDate the value for sys_coldstore.create_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.creator
     *
     * @return the value of sys_coldstore.creator
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.creator
     *
     * @param creator the value for sys_coldstore.creator
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.update_date
     *
     * @return the value of sys_coldstore.update_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.update_date
     *
     * @param updateDate the value for sys_coldstore.update_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore.updater
     *
     * @return the value of sys_coldstore.updater
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore.updater
     *
     * @param updater the value for sys_coldstore.updater
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }
}