package com.snowlink.phmapi.model;

import java.util.Date;

public class SysColdStoreContactor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore_contactor.id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore_contactor.name
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore_contactor.mobile_phone
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String mobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore_contactor.tel_phone
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String telPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore_contactor.email
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore_contactor.coldstore_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer coldstoreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore_contactor.type_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore_contactor.is_delete
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore_contactor.create_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore_contactor.create_time
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore_contactor.update_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coldstore_contactor.update_time
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore_contactor.id
     *
     * @return the value of sys_coldstore_contactor.id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore_contactor.id
     *
     * @param id the value for sys_coldstore_contactor.id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore_contactor.name
     *
     * @return the value of sys_coldstore_contactor.name
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore_contactor.name
     *
     * @param name the value for sys_coldstore_contactor.name
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore_contactor.mobile_phone
     *
     * @return the value of sys_coldstore_contactor.mobile_phone
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore_contactor.mobile_phone
     *
     * @param mobilePhone the value for sys_coldstore_contactor.mobile_phone
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore_contactor.tel_phone
     *
     * @return the value of sys_coldstore_contactor.tel_phone
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getTelPhone() {
        return telPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore_contactor.tel_phone
     *
     * @param telPhone the value for sys_coldstore_contactor.tel_phone
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setTelPhone(String telPhone) {
        this.telPhone = telPhone == null ? null : telPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore_contactor.email
     *
     * @return the value of sys_coldstore_contactor.email
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore_contactor.email
     *
     * @param email the value for sys_coldstore_contactor.email
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore_contactor.coldstore_id
     *
     * @return the value of sys_coldstore_contactor.coldstore_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getColdstoreId() {
        return coldstoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore_contactor.coldstore_id
     *
     * @param coldstoreId the value for sys_coldstore_contactor.coldstore_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setColdstoreId(Integer coldstoreId) {
        this.coldstoreId = coldstoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore_contactor.type_id
     *
     * @return the value of sys_coldstore_contactor.type_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore_contactor.type_id
     *
     * @param typeId the value for sys_coldstore_contactor.type_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore_contactor.is_delete
     *
     * @return the value of sys_coldstore_contactor.is_delete
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore_contactor.is_delete
     *
     * @param isDelete the value for sys_coldstore_contactor.is_delete
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore_contactor.create_by
     *
     * @return the value of sys_coldstore_contactor.create_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore_contactor.create_by
     *
     * @param createBy the value for sys_coldstore_contactor.create_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore_contactor.create_time
     *
     * @return the value of sys_coldstore_contactor.create_time
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore_contactor.create_time
     *
     * @param createTime the value for sys_coldstore_contactor.create_time
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore_contactor.update_by
     *
     * @return the value of sys_coldstore_contactor.update_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore_contactor.update_by
     *
     * @param updateBy the value for sys_coldstore_contactor.update_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coldstore_contactor.update_time
     *
     * @return the value of sys_coldstore_contactor.update_time
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coldstore_contactor.update_time
     *
     * @param updateTime the value for sys_coldstore_contactor.update_time
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}