package com.snowlink.phmapi.model;

import java.util.Date;

public class SysPage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_page.page_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer pageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_page.is_delete
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_page.create_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_page.create_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_page.update_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_page.update_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_page.pre_page_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer prePageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_page.level_code
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Byte levelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_page.page_name
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String pageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_page.url
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_page.description
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_page.type_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_page.icon
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_page.orderCode
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String ordercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_page.is_enable
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Boolean isEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_page.page_id
     *
     * @return the value of sys_page.page_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getPageId() {
        return pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_page.page_id
     *
     * @param pageId the value for sys_page.page_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setPageId(Integer pageId) {
        this.pageId = pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_page.is_delete
     *
     * @return the value of sys_page.is_delete
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_page.is_delete
     *
     * @param isDelete the value for sys_page.is_delete
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_page.create_by
     *
     * @return the value of sys_page.create_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_page.create_by
     *
     * @param createBy the value for sys_page.create_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_page.create_date
     *
     * @return the value of sys_page.create_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_page.create_date
     *
     * @param createDate the value for sys_page.create_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_page.update_by
     *
     * @return the value of sys_page.update_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_page.update_by
     *
     * @param updateBy the value for sys_page.update_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_page.update_date
     *
     * @return the value of sys_page.update_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_page.update_date
     *
     * @param updateDate the value for sys_page.update_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_page.pre_page_id
     *
     * @return the value of sys_page.pre_page_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getPrePageId() {
        return prePageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_page.pre_page_id
     *
     * @param prePageId the value for sys_page.pre_page_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setPrePageId(Integer prePageId) {
        this.prePageId = prePageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_page.level_code
     *
     * @return the value of sys_page.level_code
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Byte getLevelCode() {
        return levelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_page.level_code
     *
     * @param levelCode the value for sys_page.level_code
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setLevelCode(Byte levelCode) {
        this.levelCode = levelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_page.page_name
     *
     * @return the value of sys_page.page_name
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getPageName() {
        return pageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_page.page_name
     *
     * @param pageName the value for sys_page.page_name
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setPageName(String pageName) {
        this.pageName = pageName == null ? null : pageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_page.url
     *
     * @return the value of sys_page.url
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_page.url
     *
     * @param url the value for sys_page.url
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_page.description
     *
     * @return the value of sys_page.description
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_page.description
     *
     * @param description the value for sys_page.description
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_page.type_id
     *
     * @return the value of sys_page.type_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_page.type_id
     *
     * @param typeId the value for sys_page.type_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_page.icon
     *
     * @return the value of sys_page.icon
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_page.icon
     *
     * @param icon the value for sys_page.icon
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_page.orderCode
     *
     * @return the value of sys_page.orderCode
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getOrdercode() {
        return ordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_page.orderCode
     *
     * @param ordercode the value for sys_page.orderCode
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setOrdercode(String ordercode) {
        this.ordercode = ordercode == null ? null : ordercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_page.is_enable
     *
     * @return the value of sys_page.is_enable
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_page.is_enable
     *
     * @param isEnable the value for sys_page.is_enable
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }
}