package com.snowlink.phmapi.model;

public class SysUserColdStore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_coldstore.ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_coldstore.USER_ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_coldstore.coldstore_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer coldstoreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_coldstore.flag
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Boolean flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_coldstore.CREATE_DATE
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_coldstore.UPDATE_DATE
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private String updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_coldstore.ID
     *
     * @return the value of sys_user_coldstore.ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_coldstore.ID
     *
     * @param id the value for sys_user_coldstore.ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_coldstore.USER_ID
     *
     * @return the value of sys_user_coldstore.USER_ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_coldstore.USER_ID
     *
     * @param userId the value for sys_user_coldstore.USER_ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_coldstore.coldstore_id
     *
     * @return the value of sys_user_coldstore.coldstore_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getColdstoreId() {
        return coldstoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_coldstore.coldstore_id
     *
     * @param coldstoreId the value for sys_user_coldstore.coldstore_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setColdstoreId(Integer coldstoreId) {
        this.coldstoreId = coldstoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_coldstore.flag
     *
     * @return the value of sys_user_coldstore.flag
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_coldstore.flag
     *
     * @param flag the value for sys_user_coldstore.flag
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_coldstore.CREATE_DATE
     *
     * @return the value of sys_user_coldstore.CREATE_DATE
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_coldstore.CREATE_DATE
     *
     * @param createDate the value for sys_user_coldstore.CREATE_DATE
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_coldstore.UPDATE_DATE
     *
     * @return the value of sys_user_coldstore.UPDATE_DATE
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_coldstore.UPDATE_DATE
     *
     * @param updateDate the value for sys_user_coldstore.UPDATE_DATE
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }
}