package com.snowlink.phmapi.model;

public class SysUserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.USER_ROLE_ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer userRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.USER_ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.ROLE_ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.USER_ROLE_ID
     *
     * @return the value of sys_user_role.USER_ROLE_ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.USER_ROLE_ID
     *
     * @param userRoleId the value for sys_user_role.USER_ROLE_ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.USER_ID
     *
     * @return the value of sys_user_role.USER_ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.USER_ID
     *
     * @param userId the value for sys_user_role.USER_ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.ROLE_ID
     *
     * @return the value of sys_user_role.ROLE_ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.ROLE_ID
     *
     * @param roleId the value for sys_user_role.ROLE_ID
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}