package com.snowlink.phmapi.model;

import java.util.Date;

public class SysUserPage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_page.id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_page.is_delete
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_page.create_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_page.create_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_page.update_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_page.update_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_page.user_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_page.page_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    private Integer pageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_page.id
     *
     * @return the value of sys_user_page.id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_page.id
     *
     * @param id the value for sys_user_page.id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_page.is_delete
     *
     * @return the value of sys_user_page.is_delete
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_page.is_delete
     *
     * @param isDelete the value for sys_user_page.is_delete
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_page.create_by
     *
     * @return the value of sys_user_page.create_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_page.create_by
     *
     * @param createBy the value for sys_user_page.create_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_page.create_date
     *
     * @return the value of sys_user_page.create_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_page.create_date
     *
     * @param createDate the value for sys_user_page.create_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_page.update_by
     *
     * @return the value of sys_user_page.update_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_page.update_by
     *
     * @param updateBy the value for sys_user_page.update_by
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_page.update_date
     *
     * @return the value of sys_user_page.update_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_page.update_date
     *
     * @param updateDate the value for sys_user_page.update_date
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_page.user_id
     *
     * @return the value of sys_user_page.user_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_page.user_id
     *
     * @param userId the value for sys_user_page.user_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_page.page_id
     *
     * @return the value of sys_user_page.page_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public Integer getPageId() {
        return pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_page.page_id
     *
     * @param pageId the value for sys_user_page.page_id
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    public void setPageId(Integer pageId) {
        this.pageId = pageId;
    }
}