package com.snowlink.phmapi.dao;

import org.apache.ibatis.annotations.Mapper;

import com.snowlink.phmapi.model.SysColdstore;

@Mapper
public interface SysColdstoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_coldstore
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_coldstore
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int insert(SysColdstore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_coldstore
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int insertSelective(SysColdstore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_coldstore
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    SysColdstore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_coldstore
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int updateByPrimaryKeySelective(SysColdstore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_coldstore
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int updateByPrimaryKey(SysColdstore record);
}