package com.snowlink.phmapi.dao;

import org.apache.ibatis.annotations.Mapper;

import com.snowlink.phmapi.model.SysCompanyContactor;

@Mapper
public interface SysCompanyContactorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_contactor
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_contactor
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int insert(SysCompanyContactor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_contactor
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int insertSelective(SysCompanyContactor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_contactor
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    SysCompanyContactor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_contactor
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int updateByPrimaryKeySelective(SysCompanyContactor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_contactor
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int updateByPrimaryKey(SysCompanyContactor record);
}