package com.snowlink.phmapi.dao;

import org.apache.ibatis.annotations.Mapper;

import com.snowlink.phmapi.model.SysDept;

@Mapper
public interface SysDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int insert(SysDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int insertSelective(SysDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    SysDept selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int updateByPrimaryKeySelective(SysDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int updateByPrimaryKey(SysDept record);
}