package com.snowlink.phmapi.dao;

import org.apache.ibatis.annotations.Mapper;

import com.snowlink.phmapi.model.SysPage;

@Mapper
public interface SysPageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_page
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int insert(SysPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_page
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int insertSelective(SysPage record);
}