package com.snowlink.phmapi.dao;

import org.apache.ibatis.annotations.Mapper;

import com.snowlink.phmapi.model.SysRolePage;

@Mapper
public interface SysRolePageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_page
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int insert(SysRolePage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_page
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int insertSelective(SysRolePage record);
}