package com.snowlink.phmapi.dao;

import org.apache.ibatis.annotations.Mapper;

import com.snowlink.phmapi.model.SysType;

@Mapper
public interface SysTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_type
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_type
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int insert(SysType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_type
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int insertSelective(SysType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_type
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    SysType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_type
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int updateByPrimaryKeySelective(SysType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_type
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int updateByPrimaryKey(SysType record);
}