package com.snowlink.phmapi.dao;

import org.apache.ibatis.annotations.Mapper;

import com.snowlink.phmapi.model.SysUserColdStore;

@Mapper
public interface SysUserColdStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_coldstore
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_coldstore
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int insert(SysUserColdStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_coldstore
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int insertSelective(SysUserColdStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_coldstore
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    SysUserColdStore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_coldstore
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int updateByPrimaryKeySelective(SysUserColdStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_coldstore
     *
     * @mbg.generated Fri Jan 18 10:38:36 CST 2019
     */
    int updateByPrimaryKey(SysUserColdStore record);
}